/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\src\models\desktab.glb -I 
Files: .\src\models\desktab.glb [76.66MB] > C:\Users\91630\3d-modal-design\desktab-transformed.glb [537.4KB] (99%)
*/

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/desktab-transformed.glb')
  const instances = useMemo(
    () => ({
      GenericClassicTable: nodes.GenericClassicTable001,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.GenericClassicTable />
    </group>
  )
}

useGLTF.preload('/desktab-transformed.glb')
