/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\src\models\dresser2.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import Dresser2 from "./models/dresser2.glb";

export function Model(props) {
  const { nodes, materials } = useGLTF(Dresser2);
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.739, -1.025, -1.8]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.Mesh.geometry}
          material={materials["Tisch_3-03"]}
        />
        <mesh
          geometry={nodes.Mesh_1.geometry}
          material={materials["Tische Wood"]}
        />
        <group position={[180.466, 269.928, -142.37]}>
          <group position={[0, 0, 89.739]}>
            <mesh
              geometry={nodes.Mesh004.geometry}
              material={materials["Tische Wood"]}
            />
            <mesh
              geometry={nodes.Mesh004_1.geometry}
              material={materials["Tisch_3-03"]}
            />
          </group>
          <group position={[0, -179.858, 89.739]}>
            <mesh
              geometry={nodes.Mesh002.geometry}
              material={materials["Tische Wood"]}
            />
            <mesh
              geometry={nodes.Mesh002_1.geometry}
              material={materials["Tisch_3-03"]}
            />
          </group>
          <group position={[0, 0, 27.055]}>
            <mesh
              geometry={nodes.Mesh006.geometry}
              material={materials["Tische Wood"]}
            />
            <mesh
              geometry={nodes.Mesh006_1.geometry}
              material={materials["Tisch_3-03"]}
            />
          </group>
          <group position={[0, -179.858, 89.739]}>
            <mesh
              geometry={nodes.Mesh001.geometry}
              material={materials["Tische Wood"]}
            />
            <mesh
              geometry={nodes.Mesh001_1.geometry}
              material={materials["Tisch_3-03"]}
            />
          </group>
          <group position={[0, 0, -27.055]}>
            <mesh
              geometry={nodes.Mesh005.geometry}
              material={materials["Tische Wood"]}
            />
            <mesh
              geometry={nodes.Mesh005_1.geometry}
              material={materials["Tisch_3-03"]}
            />
          </group>
          <group position={[0, -179.858, -27.055]}>
            <mesh
              geometry={nodes.Mesh003.geometry}
              material={materials["Tische Wood"]}
            />
            <mesh
              geometry={nodes.Mesh003_1.geometry}
              material={materials["Tisch_3-03"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(Dresser2);
